---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: elasticsearch
    run_list: "recipe[odi-elasticsearch-wrapper]"
    attributes:
