language: ruby
rvm:
- 2.1.0
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
- echo 'Host *' >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
script:
- bundle exec rake
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: fhAXKn+d7FhuX0GbcEKeeYRm2T6T4O4nEHshay6mIphEqvsXuTUp3hJC90AydpOb1K9+m9Hn75bSFy5mhpxX/+2vx4YWaW0dAeN0kJeZIGmStVKJtVnhtxIxv1rjmIzXfkaXKiSIUKlGPuiPoVd5LncmM7kXt8gYSFtxN3eADxw=
  - secure: gzmyE0cu+e/e5FziARR3lN/2LGuNHwuDVzLfPwFNMOURduOkU1SK4EIfgjFUCBo7DwqgsiJ2KAklX69xvHoJBdY3YPyx9bPI09KvkJaOu980wwJJebOcpMP1q65d3R1CMbwEV6pXqokufwFpQTNyztWBAXkinDYJ//LJFW8Ex6A=
